Docs builder extensions #162
ardalis/Specification pull request #163
Opened 2021-09-25 22:33 UTC by vittorelli

Work in progress. Does this look okay?  
Or should the docs contain less code and move that into the sample projects in stead?

2021-09-26 00:14 UTC, ardalis requested changes
Looks great - having code in the docs is good so folks don't need to hunt down the sample separately. You can link to the sample as needed if it's something where seeing it in context of a whole app will add clarity.

2021-09-26 00:14 UTC, ardalis commented on docs/extensions/create-specification-builder.md
> +How to create your own specification builder
```suggestion

How to create your own specification builder 
```

2021-09-26 00:14 UTC, ardalis commented on docs/extensions/create-specification-builder.md
> +How to create your own specification builder
Also, although the title is all about "How" it would be great to say "Why" one would want/need to do this somewhere at the top, too.

2021-09-26 00:14 UTC, ardalis commented on docs/extensions/create-specification-builder.md
> +In order to achieve this:
```suggestion
In order to achieve this (note the `.WithTimeToLive` method):
```

2021-09-26 00:14 UTC, ardalis commented on docs/extensions/create-specification-builder.md
> +Finally, we need to take of some plumbing to implement both `` and ``. The class below uses `ConditionalWeakTable` to do the trick. An other solution is to create a base class that inherits from `Spe
```suggestion
Finally, we need to take of some plumbing to implement both `` and ``. The class below uses `ConditionalWeakTable` to do the trick. Another solution is to create a base class that inherits from `Specification<T>`.
```

2021-09-26 00:14 UTC, ardalis commented on docs/extensions/create-specification-builder.md
> +public static class SpecificationExtentions
```suggestion
public static class SpecificationExtensions
```

2021-09-26 08:57 UTC, fiseni commented
You're doing great work here @vittorelli.
While designing the infrastructure and the multi-level chain structure, never thought anyone will analyze it thoroughly or make use of it 😄 I'm glad that users are utilizing this extensibility.

2021-09-26 09:01 UTC, vittorelli commented
> Looks great - having code in the docs is good so folks don't need to hunt down the sample separately. You can link to the sample as needed if it's something where seeing it in context of a whole app will add clarity.

> Also, although the title is all about "How" it would be great to say "Why" one would want/need to do this somewhere at the top, too.

I've updated the docs so it answers to the "Why". I didn't add it as a sample in the source because I felt it would somewhat conflict with the existing `CachedRepository` sample.

2021-09-26 09:04 UTC, vittorelli commented
> You're doing great work here @vittorelli.
> While designing the infrastructure and the multi-level chain structure, never thought anyone will analyze it thoroughly or make use of it 😄 I'm glad that users are utilizing this extensibility.

@fiseni Thanks :-)  
I'm happy to contribute. It helped me a lot on several projects!

2021-09-27 15:03 UTC, ardalis approved these changes

2021-09-27 15:04 UTC, merged