Markusgnigler/remove paginate
ardalis/Specification pull request #195
Opened 2021-12-25 23:43 UTC by MarkusGnigler

I removed the obsolete Paginate method from issue [Remove obsolete Paginate builder action.](https://github.com/ardalis/Specification/issues/189).

Hope this change was sufficient.

2021-12-30 19:54 UTC, fiseni commented
Hey @MarkusGnigler,

Thank you for your help. In the issue, I also mentioned the `IsPagingEnabled` property. Please can you remove that too? It's no longer necessary.

2021-12-30 19:56 UTC, fiseni requested changes

2021-12-30 19:56 UTC, fiseni commented on Specification/src/Ardalis.Specification/Exceptions/DuplicateSkipException.cs
> +        private const string message = "Duplicate use of the Skip(). Ensure you don't use Skip() in the same specification!";
Perhaps the message should be "Duplicate use of Skip(). Ensure you don't use Skip() more than once in the same specification!".

2021-12-30 19:56 UTC, fiseni commented on Specification/src/Ardalis.Specification/Exceptions/DuplicateTakeException.cs
> +        private const string message = "Duplicate use of Take(). Ensure you don't use Take() in the same specification!";
Same as for Skip()

2021-12-31 12:32 UTC, MarkusGnigler commented
Hy @fiseni,

oh sure, it's a better exception message. Thanks for your guidance.

I also remove the `IsPagingEnabled` prop, sorry for the overlooking.

2021-12-31 13:03 UTC, MarkusGnigler commented
Should I also refactor the skip and take builder tests to use more the FluentAssertion library, or is using classic assertions the preferred approach since it's shorter?

Tests are located in:
- Ardalis.Specification.UnitTests.SpecificationBuilderExtensions_Skip
- Ardalis.Specification.UnitTests.SpecificationBuilderExtensions_Take

```cs
[Fact]
public void ThrowsDuplicateSkipException_GivenSkipUsedMoreThanOnce()
{
    Assert.Throws<DuplicateSkipException>(() => new StoreDuplicateSkipSpec());
}
```

```cs
[Fact]
public void ThrowsDuplicateSkipException_GivenSkipUsedMoreThanOnce()
{
    Action sutAction = () => new StoreDuplicateSkipSpec();

    sutAction.Should()
        .Throw<DuplicateSkipException>();
}
```

2021-12-31 17:42 UTC, fiseni approved these changes

2021-12-31 17:48 UTC, fiseni commented
I don't mind really. Since we're using fluent assertions in all other places, you can refactor it if you want, so we're consistent.

2021-12-31 18:49 UTC, MarkusGnigler commented
The consistent aspect was my first intention.

Should i scan other plaeses as well?

By me it's already evening, I'll try to commit in the next few days.

Wish you a happy new year

2021-12-31 18:57 UTC, fiseni commented
No worries, take your time. Yes, you can refactor other places too. Thank you for the help, it's appreciated.

Happy New Year!

2022-01-01 19:37 UTC, fiseni commented
Hey @MarkusGnigler. You requested a review but I don't see any new commits. Do you want me to merge it as it is, or do you want to work on the tests?

2022-01-01 21:25 UTC, MarkusGnigler commented
Hi @fiseni.

Sry, i think the requested review was a mistake.

I don't know, should i create a new PR for the test refactoring or should i stick to the existing one?

2022-01-02 15:47 UTC, MarkusGnigler commented
Hi @fiseni 

I've decided to commit the test assertions to this pr as well, since it's not that big impact.

I hope it's ok for you?

2022-01-02 15:50 UTC, fiseni approved these changes

2022-01-02 15:53 UTC, fiseni commented
Thanks for the help!

2022-01-02 15:54 UTC, merged

2022-01-02 15:57 UTC, MarkusGnigler commented
Thank you as well for your friendly communication and guidance!